name: My Github Actions Workflow
on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        echo: echo "Hello, Github Actions"
      - name: Display repo name
        echo: echo "this workflow is running in {{ github.repository}}"